# TOPIC 1: NumPy Array Creation

In [2]:
import numpy as np

In [3]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# using numpy arange

arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2 = np.random.randn(1,10)
arr2

array([[-0.77828513,  0.56569657, -0.94974278,  0.11162643,  1.10379235,
         2.58217998, -0.69125732, -0.31359892,  0.81632205,  0.03747736]])

In [7]:
arr3 = np.random.rand(1,10)
arr3

array([[0.88521034, 0.42777328, 0.33694488, 0.50433047, 0.14522789,
        0.15704477, 0.1937272 , 0.50825537, 0.07599444, 0.42789915]])

In [8]:
arr1.dtype

dtype('int32')

#  TOPIC 2: 1D, 2D, 3D Arrays in NumPy

# 1 dimensional Array

In [9]:
arr_1d = np.array([1,2,3,4,5])

arr_1d

array([1, 2, 3, 4, 5])

In [10]:
arr_1d.ndim

1

In [11]:
arr_1d = np.array([1,2,3,4,5])

arr_1d


array([1, 2, 3, 4, 5])

In [12]:
arr_1d.ndim

1

# 2 Dimensional Array

In [13]:
arr_2d = np.array([[1,2],
                   [3,4]])

arr_2d

array([[1, 2],
       [3, 4]])

In [14]:
arr_2d.ndim

2

# 3 Dimensional Array

In [15]:
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(arr_3d)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
arr_3d.ndim

3

# TOPIC 3: Array Attributes in NumPy

In [17]:
arr_2d = np.array([
    [1,2],[3,4],
    [5,6],[7,8],
    [9,10],[11,12]
])
arr_2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [18]:
arr_2d.dtype

dtype('int32')

In [19]:
arr_2d.size

12

In [20]:
arr_2d.ndim

2

In [21]:
arr_2d.shape

(6, 2)

# TOPIC 4: Vectorized Operations in NumPy

In [22]:
# in python 

a = [1,2,3]
b = [4,5,6]
c = []

for i in range(len(a)):
    c.append(a[i] + b[i])

print(c)

[5, 7, 9]


In [23]:
# in numpy
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a+b
print(c)

[5 7 9]


In [24]:
#  Vectorized Operations Examples:

a = np.array([1, 2, 3, 4])

print(a + 5)     # [6 7 8 9]
print(a - 2)     # [-1 0 1 2]
print(a * 10)    # [10 20 30 40]
print(a / 2)     # [0.5 1.0 1.5 2.0]
print(a ** 2)    # [1 4 9 16] — square

[6 7 8 9]
[-1  0  1  2]
[10 20 30 40]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


# TASK 4

In [25]:
t = np.array([2,4,6,8])

print(t + 5)
print(t * 2)
print(t - 1)
print(t ** 2)

[ 7  9 11 13]
[ 4  8 12 16]
[1 3 5 7]
[ 4 16 36 64]


## NumPy Array Creation Methods



- Task 1:
Ek array banao jo 2 se 20 tak ke even numbers contain kare using np.arange()

In [26]:
arr = np.arange(2,20,2)
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

-  Task 2:
Ek array banao jo 30 se 10 tak reverse jaye with step of 5

In [27]:
arr2 = np.arange(30,10,-5)

print(arr2)

[30 25 20 15]


## linspace
- linspace(start,stop,number)

In [28]:
import numpy as np

arr = np.linspace(0, 1, 5)
print(arr)
# [0.   0.25 0.5  0.75 1.  ]


[0.   0.25 0.5  0.75 1.  ]


- Task 1:
Ek array banao jo 1 se 5 tak 9 equally spaced values de.

In [29]:
arr3 = np.linspace(1,5,9)

arr3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

- Task 2:
Ek array banao jo 0 se 100 tak 6 values generate kare using linspace()



In [30]:
arr3 = np.linspace(0,100.6)
arr3

array([  0.        ,   2.05306122,   4.10612245,   6.15918367,
         8.2122449 ,  10.26530612,  12.31836735,  14.37142857,
        16.4244898 ,  18.47755102,  20.53061224,  22.58367347,
        24.63673469,  26.68979592,  28.74285714,  30.79591837,
        32.84897959,  34.90204082,  36.95510204,  39.00816327,
        41.06122449,  43.11428571,  45.16734694,  47.22040816,
        49.27346939,  51.32653061,  53.37959184,  55.43265306,
        57.48571429,  59.53877551,  61.59183673,  63.64489796,
        65.69795918,  67.75102041,  69.80408163,  71.85714286,
        73.91020408,  75.96326531,  78.01632653,  80.06938776,
        82.12244898,  84.1755102 ,  86.22857143,  88.28163265,
        90.33469388,  92.3877551 ,  94.44081633,  96.49387755,
        98.54693878, 100.6       ])

## zeros

## np.zeros(shape, dtype)
- shape: Array ki dimensions (rows, columns, etc.)

- dtype: Data type (optional — default is float)

- Task 1:
Ek 2x3 array bana jo zeros se filled ho.


In [31]:
arr = np.zeros((2,3))

arr

array([[0., 0., 0.],
       [0., 0., 0.]])

- Task 2:
Ek 5 elements ka array bana jo integers ho (dtype=int).


In [32]:
arr1 = np.zeros((5), dtype=int)
print(arr1)

[0 0 0 0 0]


# np.ones()

- Task Ek 2D array banao jisme 4 rows aur 2 columns ho — sirf ones hon (int type)

In [33]:
arr2 = np.ones((4,2), dtype=int)
print(arr2)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


# np.full()

## Syntax:

### np.full(shape, fill_value, dtype=None)

- Ek 2D array banao jisme 2 rows aur 4 columns hon, aur sab values 99 hon (int type)

In [34]:
arr3 = np.full((2,4), 99 , dtype=int)

print(arr3)

[[99 99 99 99]
 [99 99 99 99]]


# np.eye()
 Description:
np.eye() identity matrix banata hai — jisme diagonal me 1 hotay hain, baaki sab 0.

Identity matrix maths aur linear algebra (jaise matrix multiplication, inversion) me bohot important hoti hai.



## Syntax:

### np.eye(N, M=None, k=0, dtype=float)
## Parameters:
- N: number of rows

- M: number of columns (optional — agar na do to square matrix banti hai)

- k: diagonal shift (0 = main diagonal, +1 = upper, -1 = lower)



- Ek 5x5 identity matrix banao jisme data type int ho

In [35]:
arr4 = np.eye((5), dtype=int)

print(arr4)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# np.reshape()
## Description:
np.reshape() array ki shape ko change karta hai bina data ko chheday. Jaise ek 1D array ko 2D ya 3D me convert karna.

## Syntax:

- np.reshape(array, new_shape)
## Ya:

- array.reshape(new_shape)

In [36]:
# Example 1: 1D to 2D (3x2)

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(3, 2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [37]:
# Example 2: 1D to 3D (2x2x3)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped = arr.reshape(2, 2, 3)
print(reshaped)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


- Ek 1D array banao 1 se 12 tak, usko 2D (3x4) me reshape karo

In [38]:
arr = np.arange(1,13)
reshped = arr.reshape(3,4)

print(reshped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# np.random.rand()
## Description:
np.random.rand() se milte hain random float numbers jo range me hote hain:
**0 se 1 ke beech (0 inclusive, 1 exclusive)**

Ye values uniform distribution ke according hoti hain. Testing, visualization aur simulations me kaam aata hai.

## Syntax:
np.random.rand(shape)

In [39]:
# Ek 4x3 ka random array banao jisme values 0 aur 1 ke beech hon
arr = np.random.rand(4, 3)
print(arr)


[[0.87094157 0.4990985  0.51820744]
 [0.52438602 0.78595039 0.8957285 ]
 [0.59290213 0.12478325 0.65189276]
 [0.3692877  0.45004768 0.96876221]]


# np.random.randn()
## Description:
np.random.randn() bhi random float values deta hai, lekin normal distribution ke according — jise Gaussian distribution bhi kehte hain.

- Matlab:

Most values center (mean=0) ke paas hoti hain

Few values extreme me (positive/negative)

- Syntax:
np.random.randn(shape)

In [40]:
# Ek 3x3 ka normally distributed array banao
arr = np.random.randn(3,3)
print(arr)

[[ 0.76125124  0.76200281  0.59020285]
 [-0.99531606  1.27264057  0.7062796 ]
 [ 0.57967185  1.40191695 -0.53515859]]


# np.random.randint()
- Description:
np.random.randint() deta hai random integers kisi specific range ke andar.
- Syntax:
np.random.randint(low, high, size)

In [41]:
# Example 1: Random integers from 10 to 20 (5 values)

arr = np.random.randint(10, 20, 5)
print(arr)

[16 11 18 16 13]


In [42]:
#v Example 2: 2D array (3x3) with random integers from 0 to 100

arr = np.random.randint(0, 100, (3, 3))
print(arr)

[[37 65 22]
 [54 35 50]
 [29 95 31]]


In [43]:
# Ek 4x2 ka array banao jisme 1 se 6 ke darmiyan random integers hon
arr = np.random.randint(1, 7, (4, 2))
print(arr)


[[4 5]
 [5 5]
 [3 3]
 [2 4]]


# np.empty()
## Description:
np.empty() ek empty array create karta hai without initializing values.

- Iska matlab: array ban jaata hai, lekin uske andar random garbage values hoti hain (previous memory junk).

- Yeh fast hota hai jab tumhe placeholder array chahiye ho aur baad me values daalni ho.

- Syntax:

np.empty(shape, dtype=float)



In [44]:
# Example 1: 1D empty array of size 4

arr = np.empty(4)
print(arr)



[0.5 1.  1.5 2. ]


In [45]:
# Example 2: 2D empty array (2x3)
arr = np.empty((2, 3))
print(arr)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [1.29060871e-306 1.89146896e-307 7.56571288e-307]]


In [46]:
# Ek 3x3 ka empty array banao
arr = np.empty((3, 3))
print(arr)


[[ 0.76125124  0.76200281  0.59020285]
 [-0.99531606  1.27264057  0.7062796 ]
 [ 0.57967185  1.40191695 -0.53515859]]


# np.identity()
## Description:
np.identity() banata hai Identity Matrix:

- Diagonal me sirf 1 hota hai

- Baaki sab elements 0

- Square matrix hoti hai (n x n)

 Identity matrix ka kaam: kisi bhi matrix ko multiply karne par same matrix milti hai — jaise 1 × 5 = 5

-  Syntax:
np.identity(n)
- n: Rows and columns (equal)

In [47]:
# Example 1: 3x3 identity matrix

arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
# Example 2: 5x5 identity matrix

arr = np.identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [49]:
# Ek 4x4 identity matrix banao
arr = np.identity(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# np.tile()
- Description:
np.tile() kisi array ko repeat karta hai horizontally ya vertically.


Socho aise jaise kisi design ko pattern me copy karna ho.

- Syntax:
np.tile(array, reps)

 - array: original array

 - reps: kitni baar repeat karna hai

    - Agar int doge: horizontally repeat hota hai

    - Agar (m, n) tuple doge: vertically aur horizontally dono

In [50]:
# Example 1: 1D array ko repeat karna
arr = np.array([1,2,3])

np.tile(arr , 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [51]:
# Example 2: 2D array ko horizontally aur vertically repeat karna

arr = np.array([[1, 2], [3, 4]])
np.tile(arr, (2, 3))  # 2 rows block, 3 cols block

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [52]:
# Ek 2x2 matrix lo aur use 3x2 matrix pattern me tile karo
arr = np.array([[1,2],[3,4]])
np.tile(arr, (3,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

# np.diag()
- Description:
np.diag() ka kaam hota hai diagonal array banana.

- Ya to ek array doge — vo diagonal line pe set ho jayega.

- Ya ek matrix se sirf diagonal values nikaloge.

- Diagonal matlab:
 Jo values row aur column same ho, jaise (0,0), (1,1), (2,2), etc.

- Syntax:
np.diag(array, k=0)
array: list ya array jiski diagonal banana hai

k:

0 → main diagonal

+1 → ek upar wali diagonal

-1 → ek neeche wali diagonal

In [53]:
# Example 1: List se diagonal banana

arr = np.array([1, 2, 3])
d = np.diag(arr)
print(d)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [54]:
# Example 2: Matrix se diagonal values nikalna

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
diag_values = np.diag(arr2)
print(diag_values)

[1 5 9]


In [55]:
arr = np.array([10, 20, 30, 40])
d = np.diag(arr)
print(d)


[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


In [57]:
arr2 = np.array([[5, 7, 9],
                 [10, 12, 14],
                 [15, 17, 19]])
d2 = np.diag(arr2)
d2


array([ 5, 12, 19])

In [60]:
arr1 = np.array([[1,2,3,4,5],
                 [6,7,8,9,10]])
d = np.diag(arr1)
print(d)

[1 7]


# np.fromfunction()
- Description:
np.fromfunction() array ko banate waqt hi decide karte hain har element ka formula kya hoga.

- Har element ki value uske indexes (row, column number) se calculate hoti hai.

Bohot useful jab array ka pattern ya calculation pe based data banana ho.

## Syntax:

- np.fromfunction(function, shape, dtype=int)
  
  - function: ek aisi function jo (row, col) index se value calculate kare.

  - shape: tuple — (rows, columns)

  - dtype: data type (default int)



In [68]:
# Example 1: Simple add karna



arr = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [64]:
# Example 2: Multiplication table jesa

arr2 = np.fromfunction(lambda i, j: (i+1)*(j+1), (3,3), dtype=int)
print(arr2)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [65]:
# Task 1: Simple sum of indexes


arr = np.fromfunction(lambda i, j: i + j, (4, 4), dtype=int)
print(arr)

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [66]:
# Task 2: Create table where element = (row * 2) + (column * 3)


arr2 = np.fromfunction(lambda i, j: (i * 2) + (j * 3), (3, 5), dtype=int)
print(arr2)

[[ 0  3  6  9 12]
 [ 2  5  8 11 14]
 [ 4  7 10 13 16]]


In [67]:
# Task 3: (Challenge 🔥) Banayo array jisme har element (row number ka square) ho.


arr3 = np.fromfunction(lambda i, j: i**2, (4, 4), dtype=int)
print(arr3)

[[0 0 0 0]
 [1 1 1 1]
 [4 4 4 4]
 [9 9 9 9]]


## Task 1 — Simple Addition Grid
👉 Aisa array banao jisme har element row_index + col_index ka result ho.

Size = (4, 4)

In [74]:
arr4 = np.fromfunction(lambda i,j : i+j, (4,4))
print(arr4)

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


## Task 2 — Multiplication Grid
👉 Aisa array banao jisme har element row_index * col_index ka result ho.

Size = (3, 5)

In [80]:
arr3 = np.fromfunction(lambda i,j: (i*j), (3,5))
print(arr3)

[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


In [83]:

arr = np.fromfunction(lambda i, j: np.where((i == 0) | (i == 4) | (j == 0) | (j == 4), 1, 0), (5,5), dtype=int)
print(arr)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# np.repeat()
np.repeat(array, number_of_times)	
Har element ko repeat karta hai jitni dafa bolo

- Syntax:

np.repeat(array, repeats, axis=None)

array = Jo array tum repeat karna chahte ho

repeats = Kitni dafa har element repeat hoga

axis = 1D, 2D array ke hisab se vertical ya horizontal repeat (abhi basic me ignore kar sakte hain)



In [84]:
arr = np.array([[1, 2], [3, 4]])

new_arr = np.repeat(arr, 2)

print(new_arr)


[1 1 2 2 3 3 4 4]


In [85]:
arr = np.array([[1, 2], [3, 4]])

new_arr = np.repeat(arr, 2, axis=0)
# axis=0 ka matlab: rows repeat karo

print(new_arr)


[[1 2]
 [1 2]
 [3 4]
 [3 4]]
